### ISSUE TITLE
[xoom_core] Prepare for 1.0.0 version of sensors and package_info

### ISSUE THREAD

**Issue by amirh** [amirh/bump_to_1.0#48]
This is part of a Large Scale Change managed by [dart_lsc](https://github.com/amirh/dart_lsc).

*Do not edit the title or body of this issue, it is auto-generated and contains information used by dart_lsc.*

**Comment by amirh** [comment]
Manual intervention is needed

Executed is_change_needed script with options: `"package_info":"0.4.0"`

stdout:
```

```

stderr:
```
Unhandled exception:
FormatException: Unexpected character (at character 15)
"package_info":"0.4.0"
              ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:881:49)
#2      _parseJson (dart:convert-patch/convert_patch.dart:31:10)
#3      JsonDecoder.convert (dart:convert/json.dart:495:36)
#4      JsonCodec.decode (dart:convert/json.dart:153:41)
#5      jsonDecode (dart:convert/json.dart:96:10)
#6      MigrateTo1.isChangeNeeded (package:migrate_to_1/src/migrate_to_1.dart:23:38)
<asynchronous suspension>
#7      IsChangeNeededCommand.run (package:migrate_to_1/executable.dart:50:51)
#8      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#10     new Future.sync (dart:async/future.dart:224:31)
#11     CommandRunner.run (package:args/command_runner.dart:112:14)
#12     main (package:migrate_to_1/executable.dart:15:17)
#13     main (file:///Users/amirha/git/dart_lsc/packages/migrate_to_1/bin/migrate_to_1.dart:6:22)
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

Executed is_change_needed script with options: `"package_info":"0.4.0"`

stdout:
```

```

stderr:
```
Unhandled exception:
FormatException: Unexpected character (at character 15)
"package_info":"0.4.0"
              ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:881:49)
#2      _parseJson (dart:convert-patch/convert_patch.dart:31:10)
#3      JsonDecoder.convert (dart:convert/json.dart:495:36)
#4      JsonCodec.decode (dart:convert/json.dart:153:41)
#5      jsonDecode (dart:convert/json.dart:96:10)
#6      MigrateTo1.isChangeNeeded (package:migrate_to_1/src/migrate_to_1.dart:23:38)
<asynchronous suspension>
#7      IsChangeNeededCommand.run (package:migrate_to_1/executable.dart:50:51)
#8      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#10     new Future.sync (dart:async/future.dart:224:31)
#11     CommandRunner.run (package:args/command_runner.dart:112:14)
#12     main (package:migrate_to_1/executable.dart:15:17)
#13     main (file:///Users/amirha/git/dart_lsc/packages/migrate_to_1/bin/migrate_to_1.dart:6:22)
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

**Comment by amirh** [comment]
Further migration is not needed.

**Comment by amirh** [comment]
Further migration is not needed.
